<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="0" total="8" passed="4">
  <reporter-output>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
    </line>
  </reporter-output>
  <suite name="Functional Suite" duration-ms="120" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
    <groups>
      <group name="bvt">
        <method signature="TestCase3.fourthTest()[pri:4, instance:testcases.TestCase3@30b8a058]" name="fourthTest" class="testcases.TestCase3"/>
      </group> <!-- bvt -->
      <group name="functional">
        <method signature="TestCase1.doLogin()[pri:2, instance:testcases.TestCase1@6325a3ee]" name="doLogin" class="testcases.TestCase1"/>
        <method signature="TestCase1.doUserReg()[pri:1, instance:testcases.TestCase1@6325a3ee]" name="doUserReg" class="testcases.TestCase1"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@30b8a058]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@30b8a058]" name="doLogin" class="testcases.TestCase3"/>
        <method signature="TestCase3.thirdTest()[pri:3, instance:testcases.TestCase3@30b8a058]" name="thirdTest" class="testcases.TestCase3"/>
      </group> <!-- functional -->
      <group name="smoke">
        <method signature="TestCase2.validateTitles()[pri:0, instance:testcases.TestCase2@3b084709]" name="validateTitles" class="testcases.TestCase2"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testcases.TestCase3@30b8a058]" name="doUserReg" class="testcases.TestCase3"/>
        <method signature="TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@30b8a058]" name="doLogin" class="testcases.TestCase3"/>
        <method signature="TestCase3.thirdTest()[pri:3, instance:testcases.TestCase3@30b8a058]" name="thirdTest" class="testcases.TestCase3"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Login Test" duration-ms="41" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
      <class name="testcases.TestCase1">
        <test-method status="PASS" signature="createDBConn()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="createDBConn" is-config="true" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDBConn -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testcases.TestCase1@6325a3ee]" name="doUserReg" duration-ms="7" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testcases.TestCase1@6325a3ee]" name="doLogin" duration-ms="2" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDBConn()[pri:0, instance:testcases.TestCase1@6325a3ee]" name="closeDBConn" is-config="true" duration-ms="0" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- testcases.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="Validate Title Test" duration-ms="9" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
      <class name="testcases.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testcases.TestCase2@3b084709]" name="validateTitles" duration-ms="5" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Yahoo.com] but found [Gmail.com],
image not present expected [false] but found [true],
text box not present expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Yahoo.com] but found [Gmail.com],
image not present expected [false] but found [true],
text box not present expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testcases.TestCase2.validateTitles(TestCase2.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testcases.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency Test" duration-ms="18" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
      <class name="testcases.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testcases.TestCase3@30b8a058]" name="doUserReg" duration-ms="2" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered successfully
at org.testng.Assert.fail(Assert.java:96)
at testcases.TestCase3.doUserReg(TestCase3.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testcases.TestCase3@30b8a058]" name="doLogin" duration-ms="0" started-at="2019-02-22T10:41:48Z" depends-on-methods="testcases.TestCase3.doUserReg" finished-at="2019-02-22T10:41:48Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@30b8a058] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@30b8a058] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="thirdTest()[pri:3, instance:testcases.TestCase3@30b8a058]" name="thirdTest" duration-ms="1" started-at="2019-02-22T10:41:48Z" depends-on-methods="testcases.TestCase3.doUserReg" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method status="PASS" signature="fourthTest()[pri:4, instance:testcases.TestCase3@30b8a058]" name="fourthTest" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
      </class> <!-- testcases.TestCase3 -->
    </test> <!-- Dependency Test -->
    <test name="Failure Test" duration-ms="5" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
      <class name="testcases.TestFailure">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TestFailure@2a17b7b6]" name="setUp" is-config="true" duration-ms="16" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="doLogin()[pri:0, instance:testcases.TestFailure@2a17b7b6]" name="doLogin" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing the login test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing the login test
at org.testng.Assert.fail(Assert.java:96)
at testcases.TestFailure.doLogin(TestFailure.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="F:\screenshot\error.jpg" target="_blank"><img height=200 width=200 src="F:\screenshot\error.jpg"></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TestFailure@2a17b7b6]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-02-22T10:41:48Z" finished-at="2019-02-22T10:41:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TestFailure -->
    </test> <!-- Failure Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
